VHDL_FILES =\
	../../../lib/top/src/top.vhd \
	../../../lib/math/src/math_pkg.vhd \
	src/traffic_light.vhd \
	tb/traffic_light_tb.vhd \
	top_arch.vhd


TB=traffic_light_tb
WAVE_FILE=wave.do

VSIM_USER_ARGS=-voptargs=+acc

include ../../../util/simple_flow.mk

include ../../../util/quartus.mk
